

# Support both 32 and 64 bit builds
# if (${CMAKE_SIZEOF_VOID_P} MATCHES 8)
#   set(VIK_WRAP_LIBRARY "${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x64/SDL2main.lib")
# else ()
#   set(SDL2_LIBRARIES "${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2.lib;${CMAKE_CURRENT_LIST_DIR}/lib/x86/SDL2main.lib")
# endif ()

# string(STRIP "${SDL2_LIBRARIES}" SDL2_LIBRARIES)

set(VIK_WRAP_INCLUDE_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Build_Vik_Wrap/include/VRA/")

set(VIK_WRAP_LIBRARY_DIR "${CMAKE_CURRENT_SOURCE_DIR}/Build_Vik_Wrap/lib/")

set(VIK_WRAP_LIBRARY "-lVik_Wrap")

FIND_PACKAGE_HANDLE_STANDARD_ARGS(VIK_WRAP REQUIRED_VARS VIK_WRAP_LIBRARY VIK_WRAP_INCLUDE_DIR VIK_WRAP_LIBRARY_DIR)